### ISSUE TITLE
Week 6 - Sections

### ISSUE THREAD

**Issue by VanshitaGandhi** [VanshitaGandhi/sections#1]
Having trouble in making the text shift when the window is dragged.
@thomasjbradley

**Comment by thomasjbradley** [comment]
I see there’s a bunch of CSS targeting classes, like `.img` & `.para` but I do not see those classes in the HTML itself.

**Comment by VanshitaGandhi** [comment]
I removed the .img class since Markbot wanted an img selector and gave the second div the class="para"  @thomasjbradley

**Comment by VanshitaGandhi** [comment]
I'm sorry, I forgot to commit it, did it just now. @thomasjbradley

**Comment by thomasjbradley** [comment]
It appears you’ve been trying lots of different things and leaving the code in place—I truly appreciate the effort. But there’s just *way* too much code now—it’s usually better to delete before adding.

So, here’s a list of lines that need to be deleted:
- https://github.com/VanshitaGandhi/sections/blob/gh-pages/css/main.css#L72-L74
- https://github.com/VanshitaGandhi/sections/blob/gh-pages/css/main.css#L61-L63
- https://github.com/VanshitaGandhi/sections/blob/gh-pages/css/main.css#L51
- https://github.com/VanshitaGandhi/sections/blob/gh-pages/css/main.css#L49
- https://github.com/VanshitaGandhi/sections/blob/gh-pages/css/main.css#L34-L40
- https://github.com/VanshitaGandhi/sections/blob/gh-pages/css/main.css#L31
- https://github.com/VanshitaGandhi/sections/blob/gh-pages/css/main.css#L26-L29
- https://github.com/VanshitaGandhi/sections/blob/gh-pages/css/main.css#L12-L15

Then, paddings & margins: remember the illustration we drew in class:

- The `<div>` tags have equal padding on all four sides: `1em`
- The `<section>` only has padding on the top & bottom: `2em`
- The `<p>` & `<h2>` only have margins on the bottom: `1.5rem`

**Comment by VanshitaGandhi** [comment]
Thank you.
@thomasjbradley
